import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "./home.css";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function layout({ children }) {
  return (
    <html lang="en">
        <body>
                <div className="layout-container">
      {children}
    </div>
    
        </body>

    </html>
  )
}

export default layout