import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/sidebar";
import Header from '@/components/header';
import DashboardShell from '@/components/DashboardShell';
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }) {
  return (
    <DashboardShell>
      {children}
    </DashboardShell>
  )
}

export default Layout