import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from '@/components/header';
import Sidebar from "@/components/sidebar";
import DashboardPage from '../../components/DashboardShell';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function layout({ children }) {
  return (
<DashboardPage>
  {children}
</DashboardPage>  )
}

export default layout