import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from '@/components/header';
import Sidebar from "@/components/sidebar";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function layout({ children }) {
  return (
    <html lang="en">
        <body>
        <div className="flex"><Sidebar/></div>
                 
 <div className='flex-1 ml-69'>
          <Header />
        </div>

                <div className="layout-container">
      {children}
    </div>
    
        </body>

    </html>
  )
}

export default layout